name = "timeplus-academy-sync"
main = "worker.js"
compatibility_date = "2026-10-01"

[[d1_databases]]
binding = "AHAVA_DB"
database_name = "screen_tasks_db"
database_id = "427f12bb-1bca-47ed-825d-624ee0ed0f13"

[[d1_databases]]
binding = "TIMEPLUS_DB"
database_name = "timeplus-db"
database_id = "6453bce5-c013-4bff-a34d-52cc4bc991d4"

[triggers]
crons = ["*/5 * * * *"]
